//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Event struct {
	RowID         *int32 `sql:"primary_key"`
	StreamName    string
	StreamVersion string
	EventID       string
	EventName     string
	EventData     []byte
	HappenedOn    time.Time
	ContentType   string
}
