// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEvent = "event"

// Event mapped from table <event>
type Event struct {
	RowID         int32     `gorm:"column:row_id;primaryKey" json:"row_id"`
	StreamName    string    `gorm:"column:stream_name;not null" json:"stream_name"`
	StreamVersion string    `gorm:"column:stream_version;not null" json:"stream_version"`
	EventID       string    `gorm:"column:event_id;not null" json:"event_id"`
	EventName     string    `gorm:"column:event_name;not null" json:"event_name"`
	EventData     []byte    `gorm:"column:event_data;not null" json:"event_data"`
	HappenedOn    time.Time `gorm:"column:happened_on;not null" json:"happened_on"`
	ContentType   string    `gorm:"column:content_type;not null" json:"content_type"`
}

// TableName Event's table name
func (*Event) TableName() string {
	return TableNameEvent
}
