// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSchemaMigration = "schema_migrations"

// SchemaMigration mapped from table <schema_migrations>
type SchemaMigration struct {
	Version string `gorm:"column:version;not null" json:"version"`
	Dirty   string `gorm:"column:dirty;not null" json:"dirty"`
}

// TableName SchemaMigration's table name
func (*SchemaMigration) TableName() string {
	return TableNameSchemaMigration
}
